### PR TITLE
Add new section project using pulumi.

### PR DESCRIPTION
**Pull request by TechWatching**
Section to list open source and proprietary projects that use Pulumi. It is similar to what is done in the awesome vue list.

### CODE REVIEW

**Comment by rawkode** [comment]
@TechWatching Can you add references that confirms these projects use Pulumi?

**Comment by TechWatching** [comment]
@rawkode For Feedhive, the founder published a [youtube video](https://www.youtube.com/watch?v=SUjTIX0a1PM&t=685s) indicating the perfect stack for a SAAS, and Pulumi was mentioned for the IaC part.
image

For Daily.dev, it's mentioned in their [GitHub repo](https://github.com/dailydotdev/daily) and they have a dedicated repo with pulumi code.
image

**Review by ringods — APPROVED** [review]

**Comment by rawkode** [comment]
I'd like to see these references added to the doc. Can you use footnotes, please, @TechWatching ?

Example:

```markdown
- [Daily.dev](https://daily.dev/)[^dailydev]

[^dailydev]: [Reference](https://twitter.com/tweet_id)
```

**Review by rawkode — APPROVED** [review]

**Comment by rawkode** [comment]
Thanks @TechWatching

**Pull request merged**
